#! /bin/sh

blockdate=$(date '+%a. %d. %b. %Y')

case "$BLOCK_BUTTON" in
    1|2|3) date=$(date '+%A, %d. %B')
export TERM=xterm
#cal --color=always \
#    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
#    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
#    | tail -n +2 \
gcal  -i -q PL -s 1 -n .  | sed "s,\(Sun  .*\|Sat  .*\|:....:\|:..:\),$(tput setaf 1)&$(tput sgr0),g; s,:, ,g; s,<\(..\)>,$(tput bold) \1 $(tput sgr0)," \
    | rofi \
        -dmenu \
        -markup-rows \
        -no-fullscreen \
        -font "Monospace 12" \
        -hide-scrollbar \
        -bw 2 \
        -m -3 \
        -theme-str '#window {anchor:southeast; location: northwest;}' \

        -no-custom \
        -p "$date" > /dev/null 
    esac
echo $blockdate
date '+%d.%m.%Y'
