###############################################################
# Configuration documentation is available at
#     https://dystroy.org/broot
###############################################################

###############################################################
# Default flags
# You can set up flags you want broot to start with by
# default, for example `default_flags="ihp"` if you usually want
# to see hidden and gitignored files and the permissions (then
# if you don't want the hidden files you can launch `br -H`)
# A popular flag is the `g` one which displays git related info.
#
default_flags = "g"


###############################################################
# Verbs and shortcuts
# You can define your own commands which would be applied to
# the selection.
#
# Exemple 1: launching `tail -n` on the selected file (leaving broot)
# [[verbs]]
# name = "tail_lines"
# invocation = "tl {lines_count}"
# execution = "tail -f -n {lines_count} {file}"
#
# Exemple 2: creating a new file without leaving broot
# [[verbs]]
# name = "touch"
# invocation = "touch {new_file}"
# execution = "touch {directory}/{new_file}"
# leave_broot = false

[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "$EDITOR {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git diff {file}"
leave_broot = false

[[verbs]]
invocation = "open"
key = "ctrl-o"
execution = ":open_stay"

[[verbs]]
invocation = "home"
key = "ctrl-H"
execution = ":focus_user_home"

[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

# [[verbs]]
# key = "left"
# execution = ":parent"

# [[verbs]]
# key = "right"
# execution = ":focus"


# If you develop using git, you might like to often switch
# to the "git status" filter:
# [[verbs]]
# key = "ctrl-g"
# execution = ":toggle_git_status"

###############################################################

[skin]
default = "rgb(131, 148, 150) rgb(0, 43, 54)"          # base0 base03
tree = "rgb(88, 110, 117) none"                        # base01 default
file = "none none"                                     # default default
directory = "rgb(38, 139, 210) none bold"              # blue default bold
exe = "rgb(211, 1, 2) none"                            # red default
link = "rgb(211, 54, 130) none"                        # magenta default
pruning = "rgb(88, 110, 117) none italic"              # base01 default italic
perm__ = "rgb(88, 110, 117) none"                      # base01 default
perm_r = "none none"                                   # default default
perm_w = "none none"                                   # default default
perm_x = "none none"                                   # default default
owner = "rgb(88, 110, 117) none"                       # base01 default
group = "rgb(88, 110, 117) none"                       # base01 default
selected_line = "none rgb(7, 54, 66)"                  # default base02
char_match = "rgb(133, 153, 0) none underlined"        # green default underlined
file_error = "rgb(203, 75, 22) none italic"            # orange default italic
flag_label = "none none"                               # default default
flag_value = "rgb(181, 137, 0) none bold"              # yellow default bold
input = "none none"                                    # default default
status_error = "rgb(203, 75, 22) rgb(7, 54, 66)"       # orange base02
status_job = "rgb(108, 113, 196) rgb(7, 54, 66) bold"  # violet base02 bold
status_normal = "none rgb(7, 54, 66)"                  # default base02
status_italic = "rgb(181, 137, 0) rgb(7, 54, 66)"      # yellow base02
status_bold = "rgb(147, 161, 161) rgb(7, 54, 66) bold" # base1 base02 bold
status_code = "rgb(108, 113, 196) rgb(7, 54, 66)"      # violet base02
status_ellipsis = "none rgb(7, 54, 66)"                # default base02
scrollbar_track = "rgb(7, 54, 66) none"                # base02 default
scrollbar_thumb = "none none"                          # default default
help_paragraph = "none none"                           # default default
help_bold = "rgb(147, 161, 161) none bold"             # base1 default bold
help_italic = "rgb(147, 161, 161) none italic"         # base1 default italic
help_code = "rgb(147, 161, 161) rgb(7, 54, 66)"        # base1 base02
help_headers = "rgb(181, 137, 0) none"                 # yellow default
