theme = "modern"

[icons]
name = "awesome"
#[icons.overrides]
#bat = " | | "
#bat_full = " |X| "
#bat_charging = " |^| "
#bat_discharging = " |v| "

[[block]]
block = "backlight"
device = "intel_backlight"
[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time} {power}W"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 10

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
on_click = "/home/alteriks/.config/i3blocks/blocklets/rofi-calendar2"
