#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.dajka_krzy_ext/bin:~/.xmonad/bin
export QT_QPA_PLATFORMTHEME=qt5ct

#Add permisions for root to launch xrandr
xhost local:root

# Configure X
/home/dajka_krzy_ext/bin/Fujitsu_dock.sh

feh --bg-max  ~/fear-and-loathing.jpg ~/moonraker.jpg ~/dirtyharry.jpg &

xsetroot -cursor_name left_ptr &
#??xrdb -merge ~/.Xdefaults &
#??setxkbmap -option "ctrl:nocaps" &

# Start a window compositor. This ensures Google Chrome paints correctly.
#xcompmgr -n &

# Start the system tray
tray &
spotify &
konsole &
keepassx &

# Start a browser
#google-chrome &

# Start sound server
pulseaudio --start --log-target=syslog &

#gnome-session &
synclient PalmDetect=1
synclient PalmMinWidth=6
synclient PalmMinZ=90   
synclient TapButton3=2
synclient FingerLow=50
synclient FingerHigh=50
synclient FingerHigh=55
synclient FingerLow=50
synclient MinSpeed=1.2

